### ISSUE TITLE
Multiple output overwriting

### ISSUE THREAD

**Issue by barryswaisland-eagleeye** [Daniel-Marynicz/BehatParallelExtension#67]
Hello, fantastic module.  I'm interested in getting existing file output from this - which currently seems like it is always going to be incomplete as it would overwrite the out, given I have many scenarios and/or features:

`bit/behat -l --format=pretty --out=pretty.txt`

`pretty.txt` will only contain the last processes output.

I was thinking that would create unique files within a folder would be the best case for this, e.g. `foreach` of `buildOptionArguments` in `TaskArgumentsBuilder` might be like:

```php
if ('out' === $name) {
   if ('std' !== reset($value)) {
	//no need to pass this on as it is unseen
	continue;
   }
   $pathinfo = pathinfo(reset($value));	
   $value = 'parallel_output' . DIRECTORY_SEPARATOR
      . $pathinfo['dirname'] . DIRECTORY_SEPARATOR
      . $pathinfo['filename'] . mt_rand() . '.' . $pathinfo['extension'];
}
```

Then if there were someway to re-combine them would be the icing on cake - but the main purpose is to be able to parse results from junit automatically.  It is a shame as I have yet to think of how to still get the `html` output which would be nice.

What do you think?

**Comment by Daniel-Marynicz** [comment]
You can instead use `--out `  redirect output to file  
```bit/behat -l --format=pretty  > pretty.txt 2>&1 ```

**Comment by barryswaisland-eagleeye** [comment]
Thank you I can see how that would work with `--format=pretty`.

I should have put `--format=junit` as the example as parsing this automatically is key.

And again very much a shame that cannot output to `html`.

**Comment by Daniel-Marynicz** [comment]
junit formatter does not support this. 

You need create and register custom format. Like this  example https://stackoverflow.com/questions/8922825/how-to-set-custom-template-for-html-formatter-in-behat 
As a base for you formater you  use classes  https://github.com/Behat/Behat/tree/master/src/Behat/Behat/Output/Node/Printer/JUnit

**Comment by barryswaisland-eagleeye** [comment]
I appreciate your responses @Daniel-Marynicz - I was thinking as Junit might be considered part of behat and it would be more changes, that I'd make something like the original suggestion and then to re-combine the separate outputs - but I assume this is not a direction you would like for the module based on the suggestions so far.  I'll have a think if writing custom formatter or something else external works instead of changes to this module to make it work "out of hte box".  Thanks again for the module and your time.
